[project]
name = "agentmail-openai-terminal"
version = "0.1.0"
description = "AgentMail OpenAI terminal example"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agentmail-toolkit>=0.1.8",
    "asyncio>=3.4.3",
    "openai-agents>=0.0.9",
    "openai>=1.72.0",
]
